# TCL File Generated by Component Editor 15.0
# Wed Apr 15 18:04:16 CST 2015
# DO NOT MODIFY


# 
# terasic_bayer2rgb "terasic_bayer2rgb" v1.0
#  2015.04.15.18:04:16
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module terasic_bayer2rgb
# 
set_module_property DESCRIPTION ""
set_module_property NAME terasic_bayer2rgb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Terasic/
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME terasic_bayer2rgb
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TERASIC_Bayer2RGB
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
# add_fileset_file Bayer2RGB.v VERILOG PATH Bayer2RGB.v
add_fileset_file Bayer_LineBuffer.v VERILOG PATH Bayer_LineBuffer.v
add_fileset_file TERASIC_Bayer2RGB.v VERILOG PATH TERASIC_Bayer2RGB.v TOP_LEVEL_FILE
add_fileset_file add2.v VERILOG PATH add2.v
add_fileset_file add4.v VERILOG PATH add4.v
add_fileset_file rgb_fifo.v VERILOG PATH rgb_fifo.v


# 
# parameters
# 
add_parameter VIDEO_W INTEGER 1024
set_parameter_property VIDEO_W DEFAULT_VALUE 1024
set_parameter_property VIDEO_W DISPLAY_NAME VIDEO_W
set_parameter_property VIDEO_W TYPE INTEGER
set_parameter_property VIDEO_W UNITS None
set_parameter_property VIDEO_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_W HDL_PARAMETER true
add_parameter VIDEO_H INTEGER 768
set_parameter_property VIDEO_H DEFAULT_VALUE 768
set_parameter_property VIDEO_H DISPLAY_NAME VIDEO_H
set_parameter_property VIDEO_H TYPE INTEGER
set_parameter_property VIDEO_H UNITS None
set_parameter_property VIDEO_H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_H HDL_PARAMETER true
add_parameter RAW_BITS INTEGER 8
set_parameter_property RAW_BITS DEFAULT_VALUE 8
set_parameter_property RAW_BITS DISPLAY_NAME RAW_BITS
set_parameter_property RAW_BITS TYPE INTEGER
set_parameter_property RAW_BITS UNITS None
set_parameter_property RAW_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAW_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point din
# 
add_interface din avalon_streaming end
set_interface_property din associatedClock clock
set_interface_property din associatedReset reset
set_interface_property din dataBitsPerSymbol 8
set_interface_property din errorDescriptor ""
set_interface_property din firstSymbolInHighOrderBits true
set_interface_property din maxChannel 0
set_interface_property din readyLatency 0
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din sink_data data Input RAW_BITS
add_interface_port din sink_eop endofpacket Input 1
add_interface_port din sink_ready ready Output 1
add_interface_port din sink_sop startofpacket Input 1
add_interface_port din sink_valid valid Input 1


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 0
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout src_data data Output RAW_BITS*3
add_interface_port dout src_eop endofpacket Output 1
add_interface_port dout src_ready ready Input 1
add_interface_port dout src_sop startofpacket Output 1
add_interface_port dout src_valid valid Output 1

