/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'NIOS2_GEN2' in SOPC Builder design 'RF0002_BASE'
 * SOPC Builder design path: ../../RF0002_BASE.sopcinfo
 *
 * Generated: Sun May 10 20:23:06 EDT 2015
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * ADC_sample_store_csr configuration
 *
 */

#define ADC_SAMPLE_STORE_CSR_BASE 0x20001000
#define ADC_SAMPLE_STORE_CSR_CORE_VARIANT 0
#define ADC_SAMPLE_STORE_CSR_CSD_LENGTH 3
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_0 "CH1"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_1 "CH2"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_10 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_11 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_12 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_13 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_14 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_15 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_16 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_17 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_18 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_19 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_2 "CH3"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_20 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_21 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_22 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_23 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_24 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_25 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_26 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_27 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_28 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_29 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_3 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_30 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_31 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_32 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_33 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_34 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_35 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_36 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_37 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_38 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_39 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_4 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_40 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_41 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_42 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_43 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_44 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_45 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_46 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_47 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_48 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_49 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_5 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_50 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_51 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_52 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_53 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_54 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_55 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_56 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_57 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_58 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_59 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_6 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_60 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_61 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_62 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_63 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_7 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_8 "CH0"
#define ADC_SAMPLE_STORE_CSR_CSD_SLOT_9 "CH0"
#define ADC_SAMPLE_STORE_CSR_DUAL_ADC_MODE 0
#define ADC_SAMPLE_STORE_CSR_IRQ 0
#define ADC_SAMPLE_STORE_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ADC_SAMPLE_STORE_CSR_IS_THIS_FIRST_OR_SECOND_ADC 2
#define ADC_SAMPLE_STORE_CSR_NAME "/dev/ADC_sample_store_csr"
#define ADC_SAMPLE_STORE_CSR_PRESCALER_CH16 0
#define ADC_SAMPLE_STORE_CSR_PRESCALER_CH8 0
#define ADC_SAMPLE_STORE_CSR_REFSEL "External VREF"
#define ADC_SAMPLE_STORE_CSR_SPAN 512
#define ADC_SAMPLE_STORE_CSR_TYPE "altera_modular_adc"
#define ADC_SAMPLE_STORE_CSR_USE_CH0 0
#define ADC_SAMPLE_STORE_CSR_USE_CH1 1
#define ADC_SAMPLE_STORE_CSR_USE_CH10 0
#define ADC_SAMPLE_STORE_CSR_USE_CH11 0
#define ADC_SAMPLE_STORE_CSR_USE_CH12 0
#define ADC_SAMPLE_STORE_CSR_USE_CH13 0
#define ADC_SAMPLE_STORE_CSR_USE_CH14 0
#define ADC_SAMPLE_STORE_CSR_USE_CH15 0
#define ADC_SAMPLE_STORE_CSR_USE_CH16 0
#define ADC_SAMPLE_STORE_CSR_USE_CH2 1
#define ADC_SAMPLE_STORE_CSR_USE_CH3 1
#define ADC_SAMPLE_STORE_CSR_USE_CH4 0
#define ADC_SAMPLE_STORE_CSR_USE_CH5 0
#define ADC_SAMPLE_STORE_CSR_USE_CH6 0
#define ADC_SAMPLE_STORE_CSR_USE_CH7 0
#define ADC_SAMPLE_STORE_CSR_USE_CH8 0
#define ADC_SAMPLE_STORE_CSR_USE_CH9 0
#define ADC_SAMPLE_STORE_CSR_USE_TSD 0
#define ADC_SAMPLE_STORE_CSR_VREF 2.5
#define ALT_MODULE_CLASS_ADC_sample_store_csr altera_modular_adc


/*
 * ADC_sequencer_csr configuration
 *
 */

#define ADC_SEQUENCER_CSR_BASE 0x20001470
#define ADC_SEQUENCER_CSR_CORE_VARIANT 0
#define ADC_SEQUENCER_CSR_CSD_LENGTH 3
#define ADC_SEQUENCER_CSR_CSD_SLOT_0 "CH1"
#define ADC_SEQUENCER_CSR_CSD_SLOT_1 "CH2"
#define ADC_SEQUENCER_CSR_CSD_SLOT_10 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_11 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_12 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_13 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_14 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_15 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_16 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_17 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_18 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_19 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_2 "CH3"
#define ADC_SEQUENCER_CSR_CSD_SLOT_20 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_21 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_22 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_23 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_24 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_25 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_26 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_27 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_28 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_29 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_3 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_30 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_31 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_32 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_33 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_34 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_35 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_36 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_37 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_38 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_39 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_4 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_40 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_41 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_42 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_43 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_44 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_45 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_46 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_47 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_48 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_49 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_5 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_50 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_51 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_52 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_53 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_54 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_55 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_56 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_57 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_58 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_59 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_6 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_60 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_61 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_62 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_63 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_7 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_8 "CH0"
#define ADC_SEQUENCER_CSR_CSD_SLOT_9 "CH0"
#define ADC_SEQUENCER_CSR_DUAL_ADC_MODE 0
#define ADC_SEQUENCER_CSR_IRQ -1
#define ADC_SEQUENCER_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ADC_SEQUENCER_CSR_IS_THIS_FIRST_OR_SECOND_ADC 2
#define ADC_SEQUENCER_CSR_NAME "/dev/ADC_sequencer_csr"
#define ADC_SEQUENCER_CSR_PRESCALER_CH16 0
#define ADC_SEQUENCER_CSR_PRESCALER_CH8 0
#define ADC_SEQUENCER_CSR_REFSEL "External VREF"
#define ADC_SEQUENCER_CSR_SPAN 8
#define ADC_SEQUENCER_CSR_TYPE "altera_modular_adc"
#define ADC_SEQUENCER_CSR_USE_CH0 0
#define ADC_SEQUENCER_CSR_USE_CH1 1
#define ADC_SEQUENCER_CSR_USE_CH10 0
#define ADC_SEQUENCER_CSR_USE_CH11 0
#define ADC_SEQUENCER_CSR_USE_CH12 0
#define ADC_SEQUENCER_CSR_USE_CH13 0
#define ADC_SEQUENCER_CSR_USE_CH14 0
#define ADC_SEQUENCER_CSR_USE_CH15 0
#define ADC_SEQUENCER_CSR_USE_CH16 0
#define ADC_SEQUENCER_CSR_USE_CH2 1
#define ADC_SEQUENCER_CSR_USE_CH3 1
#define ADC_SEQUENCER_CSR_USE_CH4 0
#define ADC_SEQUENCER_CSR_USE_CH5 0
#define ADC_SEQUENCER_CSR_USE_CH6 0
#define ADC_SEQUENCER_CSR_USE_CH7 0
#define ADC_SEQUENCER_CSR_USE_CH8 0
#define ADC_SEQUENCER_CSR_USE_CH9 0
#define ADC_SEQUENCER_CSR_USE_TSD 0
#define ADC_SEQUENCER_CSR_VREF 2.5
#define ALT_MODULE_CLASS_ADC_sequencer_csr altera_modular_adc


/*
 * BLUE_LEDS configuration
 *
 */

#define ALT_MODULE_CLASS_BLUE_LEDS altera_avalon_pio
#define BLUE_LEDS_BASE 0x200013a0
#define BLUE_LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define BLUE_LEDS_BIT_MODIFYING_OUTPUT_REGISTER 1
#define BLUE_LEDS_CAPTURE 0
#define BLUE_LEDS_DATA_WIDTH 8
#define BLUE_LEDS_DO_TEST_BENCH_WIRING 0
#define BLUE_LEDS_DRIVEN_SIM_VALUE 0
#define BLUE_LEDS_EDGE_TYPE "NONE"
#define BLUE_LEDS_FREQ 50000000
#define BLUE_LEDS_HAS_IN 0
#define BLUE_LEDS_HAS_OUT 1
#define BLUE_LEDS_HAS_TRI 0
#define BLUE_LEDS_IRQ -1
#define BLUE_LEDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BLUE_LEDS_IRQ_TYPE "NONE"
#define BLUE_LEDS_NAME "/dev/BLUE_LEDS"
#define BLUE_LEDS_RESET_VALUE 0
#define BLUE_LEDS_SPAN 32
#define BLUE_LEDS_TYPE "altera_avalon_pio"


/*
 * CC2650_CTRL_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_CTRL_PIO altera_avalon_pio
#define CC2650_CTRL_PIO_BASE 0x20001300
#define CC2650_CTRL_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CC2650_CTRL_PIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC2650_CTRL_PIO_CAPTURE 0
#define CC2650_CTRL_PIO_DATA_WIDTH 1
#define CC2650_CTRL_PIO_DO_TEST_BENCH_WIRING 0
#define CC2650_CTRL_PIO_DRIVEN_SIM_VALUE 0
#define CC2650_CTRL_PIO_EDGE_TYPE "NONE"
#define CC2650_CTRL_PIO_FREQ 50000000
#define CC2650_CTRL_PIO_HAS_IN 0
#define CC2650_CTRL_PIO_HAS_OUT 1
#define CC2650_CTRL_PIO_HAS_TRI 0
#define CC2650_CTRL_PIO_IRQ -1
#define CC2650_CTRL_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_CTRL_PIO_IRQ_TYPE "NONE"
#define CC2650_CTRL_PIO_NAME "/dev/CC2650_CTRL_PIO"
#define CC2650_CTRL_PIO_RESET_VALUE 0
#define CC2650_CTRL_PIO_SPAN 32
#define CC2650_CTRL_PIO_TYPE "altera_avalon_pio"


/*
 * CC2650_IRQ_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_IRQ_PIO altera_avalon_pio
#define CC2650_IRQ_PIO_BASE 0x20001420
#define CC2650_IRQ_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define CC2650_IRQ_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CC2650_IRQ_PIO_CAPTURE 1
#define CC2650_IRQ_PIO_DATA_WIDTH 1
#define CC2650_IRQ_PIO_DO_TEST_BENCH_WIRING 0
#define CC2650_IRQ_PIO_DRIVEN_SIM_VALUE 0
#define CC2650_IRQ_PIO_EDGE_TYPE "RISING"
#define CC2650_IRQ_PIO_FREQ 50000000
#define CC2650_IRQ_PIO_HAS_IN 1
#define CC2650_IRQ_PIO_HAS_OUT 0
#define CC2650_IRQ_PIO_HAS_TRI 0
#define CC2650_IRQ_PIO_IRQ 7
#define CC2650_IRQ_PIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CC2650_IRQ_PIO_IRQ_TYPE "EDGE"
#define CC2650_IRQ_PIO_NAME "/dev/CC2650_IRQ_PIO"
#define CC2650_IRQ_PIO_RESET_VALUE 0
#define CC2650_IRQ_PIO_SPAN 16
#define CC2650_IRQ_PIO_TYPE "altera_avalon_pio"


/*
 * CC2650_SCL configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SCL altera_avalon_pio
#define CC2650_SCL_BASE 0x20001340
#define CC2650_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define CC2650_SCL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC2650_SCL_CAPTURE 0
#define CC2650_SCL_DATA_WIDTH 1
#define CC2650_SCL_DO_TEST_BENCH_WIRING 0
#define CC2650_SCL_DRIVEN_SIM_VALUE 0
#define CC2650_SCL_EDGE_TYPE "NONE"
#define CC2650_SCL_FREQ 50000000
#define CC2650_SCL_HAS_IN 0
#define CC2650_SCL_HAS_OUT 1
#define CC2650_SCL_HAS_TRI 0
#define CC2650_SCL_IRQ -1
#define CC2650_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_SCL_IRQ_TYPE "NONE"
#define CC2650_SCL_NAME "/dev/CC2650_SCL"
#define CC2650_SCL_RESET_VALUE 0
#define CC2650_SCL_SPAN 32
#define CC2650_SCL_TYPE "altera_avalon_pio"


/*
 * CC2650_SDA configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SDA altera_avalon_pio
#define CC2650_SDA_BASE 0x20001320
#define CC2650_SDA_BIT_CLEARING_EDGE_REGISTER 1
#define CC2650_SDA_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC2650_SDA_CAPTURE 0
#define CC2650_SDA_DATA_WIDTH 1
#define CC2650_SDA_DO_TEST_BENCH_WIRING 0
#define CC2650_SDA_DRIVEN_SIM_VALUE 0
#define CC2650_SDA_EDGE_TYPE "NONE"
#define CC2650_SDA_FREQ 50000000
#define CC2650_SDA_HAS_IN 0
#define CC2650_SDA_HAS_OUT 0
#define CC2650_SDA_HAS_TRI 1
#define CC2650_SDA_IRQ -1
#define CC2650_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_SDA_IRQ_TYPE "NONE"
#define CC2650_SDA_NAME "/dev/CC2650_SDA"
#define CC2650_SDA_RESET_VALUE 0
#define CC2650_SDA_SPAN 32
#define CC2650_SDA_TYPE "altera_avalon_pio"


/*
 * CC2650_SPARE_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SPARE_PIO altera_avalon_pio
#define CC2650_SPARE_PIO_BASE 0x20001440
#define CC2650_SPARE_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define CC2650_SPARE_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CC2650_SPARE_PIO_CAPTURE 0
#define CC2650_SPARE_PIO_DATA_WIDTH 10
#define CC2650_SPARE_PIO_DO_TEST_BENCH_WIRING 0
#define CC2650_SPARE_PIO_DRIVEN_SIM_VALUE 0
#define CC2650_SPARE_PIO_EDGE_TYPE "NONE"
#define CC2650_SPARE_PIO_FREQ 50000000
#define CC2650_SPARE_PIO_HAS_IN 1
#define CC2650_SPARE_PIO_HAS_OUT 0
#define CC2650_SPARE_PIO_HAS_TRI 0
#define CC2650_SPARE_PIO_IRQ -1
#define CC2650_SPARE_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_SPARE_PIO_IRQ_TYPE "NONE"
#define CC2650_SPARE_PIO_NAME "/dev/CC2650_SPARE_PIO"
#define CC2650_SPARE_PIO_RESET_VALUE 0
#define CC2650_SPARE_PIO_SPAN 16
#define CC2650_SPARE_PIO_TYPE "altera_avalon_pio"


/*
 * CC2650_SPI configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SPI altera_avalon_spi
#define CC2650_SPI_BASE 0x20001220
#define CC2650_SPI_CLOCKMULT 1
#define CC2650_SPI_CLOCKPHASE 0
#define CC2650_SPI_CLOCKPOLARITY 0
#define CC2650_SPI_CLOCKUNITS "Hz"
#define CC2650_SPI_DATABITS 8
#define CC2650_SPI_DATAWIDTH 16
#define CC2650_SPI_DELAYMULT "1.0E-9"
#define CC2650_SPI_DELAYUNITS "ns"
#define CC2650_SPI_EXTRADELAY 0
#define CC2650_SPI_INSERT_SYNC 1
#define CC2650_SPI_IRQ 6
#define CC2650_SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CC2650_SPI_ISMASTER 0
#define CC2650_SPI_LSBFIRST 0
#define CC2650_SPI_NAME "/dev/CC2650_SPI"
#define CC2650_SPI_NUMSLAVES 1
#define CC2650_SPI_PREFIX "spi_"
#define CC2650_SPI_SPAN 32
#define CC2650_SPI_SYNC_REG_DEPTH 2
#define CC2650_SPI_TARGETCLOCK 4000000u
#define CC2650_SPI_TARGETSSDELAY "0.0"
#define CC2650_SPI_TYPE "altera_avalon_spi"


/*
 * CC2650_SSID_HIGH configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SSID_HIGH altera_avalon_pio
#define CC2650_SSID_HIGH_BASE 0x20001260
#define CC2650_SSID_HIGH_BIT_CLEARING_EDGE_REGISTER 0
#define CC2650_SSID_HIGH_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC2650_SSID_HIGH_CAPTURE 0
#define CC2650_SSID_HIGH_DATA_WIDTH 32
#define CC2650_SSID_HIGH_DO_TEST_BENCH_WIRING 0
#define CC2650_SSID_HIGH_DRIVEN_SIM_VALUE 0
#define CC2650_SSID_HIGH_EDGE_TYPE "NONE"
#define CC2650_SSID_HIGH_FREQ 50000000
#define CC2650_SSID_HIGH_HAS_IN 0
#define CC2650_SSID_HIGH_HAS_OUT 1
#define CC2650_SSID_HIGH_HAS_TRI 0
#define CC2650_SSID_HIGH_IRQ -1
#define CC2650_SSID_HIGH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_SSID_HIGH_IRQ_TYPE "NONE"
#define CC2650_SSID_HIGH_NAME "/dev/CC2650_SSID_HIGH"
#define CC2650_SSID_HIGH_RESET_VALUE 0
#define CC2650_SSID_HIGH_SPAN 32
#define CC2650_SSID_HIGH_TYPE "altera_avalon_pio"


/*
 * CC2650_SSID_LOW configuration
 *
 */

#define ALT_MODULE_CLASS_CC2650_SSID_LOW altera_avalon_pio
#define CC2650_SSID_LOW_BASE 0x20001280
#define CC2650_SSID_LOW_BIT_CLEARING_EDGE_REGISTER 0
#define CC2650_SSID_LOW_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC2650_SSID_LOW_CAPTURE 0
#define CC2650_SSID_LOW_DATA_WIDTH 32
#define CC2650_SSID_LOW_DO_TEST_BENCH_WIRING 0
#define CC2650_SSID_LOW_DRIVEN_SIM_VALUE 0
#define CC2650_SSID_LOW_EDGE_TYPE "NONE"
#define CC2650_SSID_LOW_FREQ 50000000
#define CC2650_SSID_LOW_HAS_IN 0
#define CC2650_SSID_LOW_HAS_OUT 1
#define CC2650_SSID_LOW_HAS_TRI 0
#define CC2650_SSID_LOW_IRQ -1
#define CC2650_SSID_LOW_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC2650_SSID_LOW_IRQ_TYPE "NONE"
#define CC2650_SSID_LOW_NAME "/dev/CC2650_SSID_LOW"
#define CC2650_SSID_LOW_RESET_VALUE 0
#define CC2650_SSID_LOW_SPAN 32
#define CC2650_SSID_LOW_TYPE "altera_avalon_pio"


/*
 * CC3100_CTRL_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_CC3100_CTRL_PIO altera_avalon_pio
#define CC3100_CTRL_PIO_BASE 0x20001360
#define CC3100_CTRL_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CC3100_CTRL_PIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CC3100_CTRL_PIO_CAPTURE 0
#define CC3100_CTRL_PIO_DATA_WIDTH 2
#define CC3100_CTRL_PIO_DO_TEST_BENCH_WIRING 0
#define CC3100_CTRL_PIO_DRIVEN_SIM_VALUE 0
#define CC3100_CTRL_PIO_EDGE_TYPE "NONE"
#define CC3100_CTRL_PIO_FREQ 50000000
#define CC3100_CTRL_PIO_HAS_IN 0
#define CC3100_CTRL_PIO_HAS_OUT 1
#define CC3100_CTRL_PIO_HAS_TRI 0
#define CC3100_CTRL_PIO_IRQ -1
#define CC3100_CTRL_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CC3100_CTRL_PIO_IRQ_TYPE "NONE"
#define CC3100_CTRL_PIO_NAME "/dev/CC3100_CTRL_PIO"
#define CC3100_CTRL_PIO_RESET_VALUE 0
#define CC3100_CTRL_PIO_SPAN 32
#define CC3100_CTRL_PIO_TYPE "altera_avalon_pio"


/*
 * CC3100_IRQ_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_CC3100_IRQ_PIO altera_avalon_pio
#define CC3100_IRQ_PIO_BASE 0x20001450
#define CC3100_IRQ_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define CC3100_IRQ_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CC3100_IRQ_PIO_CAPTURE 1
#define CC3100_IRQ_PIO_DATA_WIDTH 1
#define CC3100_IRQ_PIO_DO_TEST_BENCH_WIRING 0
#define CC3100_IRQ_PIO_DRIVEN_SIM_VALUE 0
#define CC3100_IRQ_PIO_EDGE_TYPE "RISING"
#define CC3100_IRQ_PIO_FREQ 50000000
#define CC3100_IRQ_PIO_HAS_IN 1
#define CC3100_IRQ_PIO_HAS_OUT 0
#define CC3100_IRQ_PIO_HAS_TRI 0
#define CC3100_IRQ_PIO_IRQ 5
#define CC3100_IRQ_PIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CC3100_IRQ_PIO_IRQ_TYPE "EDGE"
#define CC3100_IRQ_PIO_NAME "/dev/CC3100_IRQ_PIO"
#define CC3100_IRQ_PIO_RESET_VALUE 0
#define CC3100_IRQ_PIO_SPAN 16
#define CC3100_IRQ_PIO_TYPE "altera_avalon_pio"


/*
 * CC3100_SPI configuration
 *
 */

#define ALT_MODULE_CLASS_CC3100_SPI altera_avalon_spi
#define CC3100_SPI_BASE 0x20001240
#define CC3100_SPI_CLOCKMULT 1
#define CC3100_SPI_CLOCKPHASE 0
#define CC3100_SPI_CLOCKPOLARITY 0
#define CC3100_SPI_CLOCKUNITS "Hz"
#define CC3100_SPI_DATABITS 8
#define CC3100_SPI_DATAWIDTH 16
#define CC3100_SPI_DELAYMULT "1.0E-9"
#define CC3100_SPI_DELAYUNITS "ns"
#define CC3100_SPI_EXTRADELAY 0
#define CC3100_SPI_INSERT_SYNC 0
#define CC3100_SPI_IRQ 4
#define CC3100_SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CC3100_SPI_ISMASTER 1
#define CC3100_SPI_LSBFIRST 0
#define CC3100_SPI_NAME "/dev/CC3100_SPI"
#define CC3100_SPI_NUMSLAVES 1
#define CC3100_SPI_PREFIX "spi_"
#define CC3100_SPI_SPAN 32
#define CC3100_SPI_SYNC_REG_DEPTH 2
#define CC3100_SPI_TARGETCLOCK 10000000u
#define CC3100_SPI_TARGETSSDELAY "0.0"
#define CC3100_SPI_TYPE "altera_avalon_spi"


/*
 * CC3100_UART configuration
 *
 */

#define ALT_MODULE_CLASS_CC3100_UART altera_avalon_uart
#define CC3100_UART_BASE 0x20001380
#define CC3100_UART_BAUD 115200
#define CC3100_UART_DATA_BITS 8
#define CC3100_UART_FIXED_BAUD 1
#define CC3100_UART_FREQ 50000000
#define CC3100_UART_IRQ 3
#define CC3100_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CC3100_UART_NAME "/dev/CC3100_UART"
#define CC3100_UART_PARITY 'N'
#define CC3100_UART_SIM_CHAR_STREAM ""
#define CC3100_UART_SIM_TRUE_BAUD 0
#define CC3100_UART_SPAN 32
#define CC3100_UART_STOP_BITS 1
#define CC3100_UART_SYNC_REG_DEPTH 2
#define CC3100_UART_TYPE "altera_avalon_uart"
#define CC3100_UART_USE_CTS_RTS 1
#define CC3100_UART_USE_EOP_REGISTER 0


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x20000820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1e
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x10000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1e
#define ALT_CPU_NAME "NIOS2_GEN2"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x10000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x20000820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1e
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x10000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1e
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x10000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_UART
#define __ALTERA_MEM_IF_DDR3_EMIF
#define __ALTERA_MODULAR_ADC
#define __ALTERA_NIOS2_GEN2


/*
 * G_SENSOR_PIO configuration
 *
 */

#define ALT_MODULE_CLASS_G_SENSOR_PIO altera_avalon_pio
#define G_SENSOR_PIO_BASE 0x200013c0
#define G_SENSOR_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define G_SENSOR_PIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define G_SENSOR_PIO_CAPTURE 0
#define G_SENSOR_PIO_DATA_WIDTH 2
#define G_SENSOR_PIO_DO_TEST_BENCH_WIRING 0
#define G_SENSOR_PIO_DRIVEN_SIM_VALUE 0
#define G_SENSOR_PIO_EDGE_TYPE "NONE"
#define G_SENSOR_PIO_FREQ 50000000
#define G_SENSOR_PIO_HAS_IN 0
#define G_SENSOR_PIO_HAS_OUT 1
#define G_SENSOR_PIO_HAS_TRI 0
#define G_SENSOR_PIO_IRQ -1
#define G_SENSOR_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define G_SENSOR_PIO_IRQ_TYPE "NONE"
#define G_SENSOR_PIO_NAME "/dev/G_SENSOR_PIO"
#define G_SENSOR_PIO_RESET_VALUE 0
#define G_SENSOR_PIO_SPAN 32
#define G_SENSOR_PIO_TYPE "altera_avalon_pio"


/*
 * JTAG_UART configuration
 *
 */

#define ALT_MODULE_CLASS_JTAG_UART altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x20001480
#define JTAG_UART_IRQ 1
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/JTAG_UART"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * RF002_EEPROM_SCL configuration
 *
 */

#define ALT_MODULE_CLASS_RF002_EEPROM_SCL altera_avalon_pio
#define RF002_EEPROM_SCL_BASE 0x200012e0
#define RF002_EEPROM_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define RF002_EEPROM_SCL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define RF002_EEPROM_SCL_CAPTURE 0
#define RF002_EEPROM_SCL_DATA_WIDTH 1
#define RF002_EEPROM_SCL_DO_TEST_BENCH_WIRING 0
#define RF002_EEPROM_SCL_DRIVEN_SIM_VALUE 0
#define RF002_EEPROM_SCL_EDGE_TYPE "NONE"
#define RF002_EEPROM_SCL_FREQ 50000000
#define RF002_EEPROM_SCL_HAS_IN 0
#define RF002_EEPROM_SCL_HAS_OUT 1
#define RF002_EEPROM_SCL_HAS_TRI 0
#define RF002_EEPROM_SCL_IRQ -1
#define RF002_EEPROM_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RF002_EEPROM_SCL_IRQ_TYPE "NONE"
#define RF002_EEPROM_SCL_NAME "/dev/RF002_EEPROM_SCL"
#define RF002_EEPROM_SCL_RESET_VALUE 0
#define RF002_EEPROM_SCL_SPAN 32
#define RF002_EEPROM_SCL_TYPE "altera_avalon_pio"


/*
 * RF002_EEPROM_SDA configuration
 *
 */

#define ALT_MODULE_CLASS_RF002_EEPROM_SDA altera_avalon_pio
#define RF002_EEPROM_SDA_BASE 0x200012c0
#define RF002_EEPROM_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define RF002_EEPROM_SDA_BIT_MODIFYING_OUTPUT_REGISTER 1
#define RF002_EEPROM_SDA_CAPTURE 0
#define RF002_EEPROM_SDA_DATA_WIDTH 1
#define RF002_EEPROM_SDA_DO_TEST_BENCH_WIRING 0
#define RF002_EEPROM_SDA_DRIVEN_SIM_VALUE 0
#define RF002_EEPROM_SDA_EDGE_TYPE "NONE"
#define RF002_EEPROM_SDA_FREQ 50000000
#define RF002_EEPROM_SDA_HAS_IN 0
#define RF002_EEPROM_SDA_HAS_OUT 0
#define RF002_EEPROM_SDA_HAS_TRI 1
#define RF002_EEPROM_SDA_IRQ -1
#define RF002_EEPROM_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RF002_EEPROM_SDA_IRQ_TYPE "NONE"
#define RF002_EEPROM_SDA_NAME "/dev/RF002_EEPROM_SDA"
#define RF002_EEPROM_SDA_RESET_VALUE 0
#define RF002_EEPROM_SDA_SPAN 32
#define RF002_EEPROM_SDA_TYPE "altera_avalon_pio"


/*
 * RH_TEMP_DRDY configuration
 *
 */

#define ALT_MODULE_CLASS_RH_TEMP_DRDY altera_avalon_pio
#define RH_TEMP_DRDY_BASE 0x20001460
#define RH_TEMP_DRDY_BIT_CLEARING_EDGE_REGISTER 0
#define RH_TEMP_DRDY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define RH_TEMP_DRDY_CAPTURE 1
#define RH_TEMP_DRDY_DATA_WIDTH 1
#define RH_TEMP_DRDY_DO_TEST_BENCH_WIRING 0
#define RH_TEMP_DRDY_DRIVEN_SIM_VALUE 0
#define RH_TEMP_DRDY_EDGE_TYPE "FALLING"
#define RH_TEMP_DRDY_FREQ 50000000
#define RH_TEMP_DRDY_HAS_IN 1
#define RH_TEMP_DRDY_HAS_OUT 0
#define RH_TEMP_DRDY_HAS_TRI 0
#define RH_TEMP_DRDY_IRQ 2
#define RH_TEMP_DRDY_IRQ_INTERRUPT_CONTROLLER_ID 0
#define RH_TEMP_DRDY_IRQ_TYPE "EDGE"
#define RH_TEMP_DRDY_NAME "/dev/RH_TEMP_DRDY"
#define RH_TEMP_DRDY_RESET_VALUE 0
#define RH_TEMP_DRDY_SPAN 16
#define RH_TEMP_DRDY_TYPE "altera_avalon_pio"


/*
 * RH_TEMP_SCL configuration
 *
 */

#define ALT_MODULE_CLASS_RH_TEMP_SCL altera_avalon_pio
#define RH_TEMP_SCL_BASE 0x20001400
#define RH_TEMP_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define RH_TEMP_SCL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define RH_TEMP_SCL_CAPTURE 0
#define RH_TEMP_SCL_DATA_WIDTH 1
#define RH_TEMP_SCL_DO_TEST_BENCH_WIRING 0
#define RH_TEMP_SCL_DRIVEN_SIM_VALUE 0
#define RH_TEMP_SCL_EDGE_TYPE "NONE"
#define RH_TEMP_SCL_FREQ 50000000
#define RH_TEMP_SCL_HAS_IN 0
#define RH_TEMP_SCL_HAS_OUT 1
#define RH_TEMP_SCL_HAS_TRI 0
#define RH_TEMP_SCL_IRQ -1
#define RH_TEMP_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RH_TEMP_SCL_IRQ_TYPE "NONE"
#define RH_TEMP_SCL_NAME "/dev/RH_TEMP_SCL"
#define RH_TEMP_SCL_RESET_VALUE 0
#define RH_TEMP_SCL_SPAN 32
#define RH_TEMP_SCL_TYPE "altera_avalon_pio"


/*
 * RH_TEMP_SDA configuration
 *
 */

#define ALT_MODULE_CLASS_RH_TEMP_SDA altera_avalon_pio
#define RH_TEMP_SDA_BASE 0x200013e0
#define RH_TEMP_SDA_BIT_CLEARING_EDGE_REGISTER 0
#define RH_TEMP_SDA_BIT_MODIFYING_OUTPUT_REGISTER 1
#define RH_TEMP_SDA_CAPTURE 0
#define RH_TEMP_SDA_DATA_WIDTH 1
#define RH_TEMP_SDA_DO_TEST_BENCH_WIRING 0
#define RH_TEMP_SDA_DRIVEN_SIM_VALUE 0
#define RH_TEMP_SDA_EDGE_TYPE "NONE"
#define RH_TEMP_SDA_FREQ 50000000
#define RH_TEMP_SDA_HAS_IN 0
#define RH_TEMP_SDA_HAS_OUT 0
#define RH_TEMP_SDA_HAS_TRI 1
#define RH_TEMP_SDA_IRQ -1
#define RH_TEMP_SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RH_TEMP_SDA_IRQ_TYPE "NONE"
#define RH_TEMP_SDA_NAME "/dev/RH_TEMP_SDA"
#define RH_TEMP_SDA_RESET_VALUE 0
#define RH_TEMP_SDA_SPAN 32
#define RH_TEMP_SDA_TYPE "altera_avalon_pio"


/*
 * SYSID configuration
 *
 */

#define ALT_MODULE_CLASS_SYSID altera_avalon_sysid_qsys
#define SYSID_BASE 0x20001478
#define SYSID_ID -557187059
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/SYSID"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1431293670
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * SYS_RST_OUT_N configuration
 *
 */

#define ALT_MODULE_CLASS_SYS_RST_OUT_N altera_avalon_pio
#define SYS_RST_OUT_N_BASE 0x200012a0
#define SYS_RST_OUT_N_BIT_CLEARING_EDGE_REGISTER 0
#define SYS_RST_OUT_N_BIT_MODIFYING_OUTPUT_REGISTER 1
#define SYS_RST_OUT_N_CAPTURE 0
#define SYS_RST_OUT_N_DATA_WIDTH 1
#define SYS_RST_OUT_N_DO_TEST_BENCH_WIRING 0
#define SYS_RST_OUT_N_DRIVEN_SIM_VALUE 0
#define SYS_RST_OUT_N_EDGE_TYPE "NONE"
#define SYS_RST_OUT_N_FREQ 50000000
#define SYS_RST_OUT_N_HAS_IN 0
#define SYS_RST_OUT_N_HAS_OUT 1
#define SYS_RST_OUT_N_HAS_TRI 0
#define SYS_RST_OUT_N_IRQ -1
#define SYS_RST_OUT_N_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYS_RST_OUT_N_IRQ_TYPE "NONE"
#define SYS_RST_OUT_N_NAME "/dev/SYS_RST_OUT_N"
#define SYS_RST_OUT_N_RESET_VALUE 1
#define SYS_RST_OUT_N_SPAN 32
#define SYS_RST_OUT_N_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/JTAG_UART"
#define ALT_STDERR_BASE 0x20001480
#define ALT_STDERR_DEV JTAG_UART
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/JTAG_UART"
#define ALT_STDIN_BASE 0x20001480
#define ALT_STDIN_DEV JTAG_UART
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/JTAG_UART"
#define ALT_STDOUT_BASE 0x20001480
#define ALT_STDOUT_DEV JTAG_UART
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "RF0002_BASE"


/*
 * ddr3_status configuration
 *
 */

#define ALT_MODULE_CLASS_ddr3_status altera_avalon_pio
#define DDR3_STATUS_BASE 0x20001430
#define DDR3_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define DDR3_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDR3_STATUS_CAPTURE 0
#define DDR3_STATUS_DATA_WIDTH 3
#define DDR3_STATUS_DO_TEST_BENCH_WIRING 0
#define DDR3_STATUS_DRIVEN_SIM_VALUE 0
#define DDR3_STATUS_EDGE_TYPE "NONE"
#define DDR3_STATUS_FREQ 50000000
#define DDR3_STATUS_HAS_IN 1
#define DDR3_STATUS_HAS_OUT 0
#define DDR3_STATUS_HAS_TRI 0
#define DDR3_STATUS_IRQ -1
#define DDR3_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDR3_STATUS_IRQ_TYPE "NONE"
#define DDR3_STATUS_NAME "/dev/ddr3_status"
#define DDR3_STATUS_RESET_VALUE 0
#define DDR3_STATUS_SPAN 16
#define DDR3_STATUS_TYPE "altera_avalon_pio"


/*
 * deca_rev_pio configuration
 *
 */

#define ALT_MODULE_CLASS_deca_rev_pio altera_avalon_pio
#define DECA_REV_PIO_BASE 0x0
#define DECA_REV_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define DECA_REV_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DECA_REV_PIO_CAPTURE 0
#define DECA_REV_PIO_DATA_WIDTH 8
#define DECA_REV_PIO_DO_TEST_BENCH_WIRING 0
#define DECA_REV_PIO_DRIVEN_SIM_VALUE 0
#define DECA_REV_PIO_EDGE_TYPE "NONE"
#define DECA_REV_PIO_FREQ 50000000
#define DECA_REV_PIO_HAS_IN 1
#define DECA_REV_PIO_HAS_OUT 0
#define DECA_REV_PIO_HAS_TRI 0
#define DECA_REV_PIO_IRQ -1
#define DECA_REV_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DECA_REV_PIO_IRQ_TYPE "NONE"
#define DECA_REV_PIO_NAME "/dev/deca_rev_pio"
#define DECA_REV_PIO_RESET_VALUE 0
#define DECA_REV_PIO_SPAN 16
#define DECA_REV_PIO_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * mem_if_ddr3_emif_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mem_if_ddr3_emif_0 altera_mem_if_ddr3_emif
#define MEM_IF_DDR3_EMIF_0_BASE 0x10000000
#define MEM_IF_DDR3_EMIF_0_IRQ -1
#define MEM_IF_DDR3_EMIF_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MEM_IF_DDR3_EMIF_0_NAME "/dev/mem_if_ddr3_emif_0"
#define MEM_IF_DDR3_EMIF_0_SPAN 268435456
#define MEM_IF_DDR3_EMIF_0_TYPE "altera_mem_if_ddr3_emif"


/*
 * spi_gsensor configuration
 *
 */

#define ALT_MODULE_CLASS_spi_gsensor altera_avalon_spi
#define SPI_GSENSOR_BASE 0x20001200
#define SPI_GSENSOR_CLOCKMULT 1
#define SPI_GSENSOR_CLOCKPHASE 1
#define SPI_GSENSOR_CLOCKPOLARITY 1
#define SPI_GSENSOR_CLOCKUNITS "Hz"
#define SPI_GSENSOR_DATABITS 16
#define SPI_GSENSOR_DATAWIDTH 16
#define SPI_GSENSOR_DELAYMULT "1.0E-9"
#define SPI_GSENSOR_DELAYUNITS "ns"
#define SPI_GSENSOR_EXTRADELAY 0
#define SPI_GSENSOR_INSERT_SYNC 0
#define SPI_GSENSOR_IRQ 8
#define SPI_GSENSOR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_GSENSOR_ISMASTER 1
#define SPI_GSENSOR_LSBFIRST 0
#define SPI_GSENSOR_NAME "/dev/spi_gsensor"
#define SPI_GSENSOR_NUMSLAVES 1
#define SPI_GSENSOR_PREFIX "spi_"
#define SPI_GSENSOR_SPAN 32
#define SPI_GSENSOR_SYNC_REG_DEPTH 2
#define SPI_GSENSOR_TARGETCLOCK 20000000u
#define SPI_GSENSOR_TARGETSSDELAY "0.0"
#define SPI_GSENSOR_TYPE "altera_avalon_spi"

#endif /* __SYSTEM_H_ */
